[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/otp/send"
  to = "/.netlify/functions/send-otp"
  status = 200
  force = true

[[redirects]]
  from = "/api/otp/verify"
  to = "/.netlify/functions/verify-otp"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Long cache headers for static images
[[headers]]
  for = "/gallery/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/banner/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/feature/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"



