import { useNavigate, useParams } from "react-router-dom";
import ProductList from "../components/products/ProductList";
import CategoryCard from "../components/products/CategoryCard";

const products = [
  {
    id: 1,
    name: "Absolute-Black-Granite",
    image: "/grenite/Absolute-Black-Granite.jpg",
    category: "Granite",
    isNew: true,
  },
  {
    id: 2,
    name: "African-Sparkle",
    image: "/grenite/African-Sparkle-1.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 3,
    name: "Alaska gold",
    image: "/grenite/Alaska gold-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 4,
    name: "Alaska pink",
    image: "/grenite/Alaska pink-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 8,
    name: "Alpine white",
    image: "/grenite/Alpine white (2).jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 15,
    name: "antique-brown",
    image: "/grenite/antique-brown.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 16,
    name: "Armani gold",
    image: "/grenite/Armani gold.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 17,
    name: "Armani great",
    image: "/grenite/Armani great -p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 18,
    name: "Armani grey",
    image: "/grenite/Armani grey -p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },

  {
    id: 19,
    name: "azul-nuevo",
    image: "/grenite/azul-nuevo.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 20,
    name: "Belvedere",
    image: "/grenite/Belvedere.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 21,
    name: "Bianco typhoon",
    image: "/grenite/Bianco typhoon 1081-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 22,
    name: "Black-Galaxy-Granite",
    image: "/grenite/Black-Galaxy-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 23,
    name: "Black-Marquina",
    image: "/grenite/Black-Marquina.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 24,
    name: "black-pebble",
    image: "/grenite/black-pebble.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 25,
    name: "Grey dunes",
    image: "/grenite/Blue dunes-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 26,
    name: "Blue dunes",
    image: "/grenite/Blue dunes.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 29,
    name: "blue-flower",
    image: "/grenite/blue-flower.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 30,
    name: "blue-in-night",
    image: "/grenite/blue-in-night.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 31,
    name: "blue-pearl",
    image: "/grenite/blue-pearl.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 32,
    name: "Blue-Topaz",
    image: "/grenite/Blue-Topaz.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 33,
    name: "branco-ceara",
    image: "/grenite/branco-ceara.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 34,
    name: "Candle brass",
    image: "/grenite/Candle brass.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 36,
    name: "Champagne gold",
    image: "/grenite/Champagne gold-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 37,
    name: "champagne-gold-2",
    image: "/grenite/champagne-gold.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 38,
    name: "Cheema-Pink",
    image: "/grenite/Cheema-Pink.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 39,
    name: "Cheema-White",
    image: "/grenite/Cheema-White.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 41,
    name: "Coin-Black",
    image: "/grenite/Coin-Black.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 42,
    name: "copanhagen",
    image: "/grenite/copanhagen.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 43,
    name: "Copenhagen cream ",
    image: "/grenite/Copenhagen cream -p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 46,
    name: "cotton-white",
    image: "/grenite/cotton-white.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 47,
    name: "Crystal-Grey-ROYAL-BEIZ-2",
    image: "/grenite/Crystal-Grey-ROYAL-BEIZ-2.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 48,
    name: "Crystal-Yellow-Granite",
    image: "/grenite/Crystal-Yellow-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 49,
    name: "Crystallo",
    image: "/grenite/Crystallo.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 50,
    name: "Desert-Brown",
    image: "/grenite/Desert-Brown-Granite-Slab-Granix.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 51,
    name: "Desert-Green",
    image: "/grenite/Desert-Green.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 52,
    name: "Devgarh-Black-Granite",
    image: "/grenite/Devgarh-Black-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 53,
    name: "Diamond-Fall",
    image: "/grenite/Diamond-Fall.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 54,
    name: "Dior white",
    image: "/grenite/Dior white.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 55,
    name: "emerald-pearl",
    image: "/grenite/emerald-pearl.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 56,
    name: "Exuberant-Brown",
    image: "/grenite/Exuberant-Brown.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 57,
    name: "Fantasy-Gold",
    image: "/grenite/Fantasy-Gold.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 58,
    name: "French-Green",
    image: "/grenite/French-Green.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 59,
    name: "Gem-Red-Granite",
    image: "/grenite/Gem-Red-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 60,
    name: "Ghibli-Granite",
    image: "/grenite/Ghibli-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 61,
    name: "Giallo-Florito",
    image: "/grenite/Giallo-Florito.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 62,
    name: "Golden Persia",
    image: "/grenite/Golden Persia-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 63,
    name: "Golden-Torronci",
    image: "/grenite/Golden-Torronci.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 65,
    name: "himalayan-green",
    image: "/grenite/himalayan-green.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 66,
    name: "Ice Crystal",
    image: "/grenite/Ice Crystal-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 67,
    name: "Imperial-Blue",
    image: "/grenite/Imperial-Blue.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 68,
    name: "Imperial-Red-Granite",
    image: "/grenite/Imperial-Red-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 69,
    name: "Jhansi-Red",
    image: "/grenite/Jhansi-Red.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 70,
    name: "Jupiter-Red-Granite",
    image: "/grenite/Jupiter-Red-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 71,
    name: "Kosmus",
    image: "/grenite/Kosmus.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 72,
    name: "Lakha-Red-Granite",
    image: "/grenite/Lakha-Red-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 73,
    name: "Lava oro ",
    image: "/grenite/Lava oro -p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 74,
    name: "Lava oro extra",
    image: "/grenite/Lava oro extra -p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 75,
    name: "Lemurian",
    image: "/grenite/Lemurian.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 76,
    name: "lenon-blue",
    image: "/grenite/lenon-blue.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 77,
    name: "Magic-black",
    image: "/grenite/Magic-black.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 79,
    name: "monk-gold",
    image: "/grenite/monk-gold.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 80,
    name: "mont-blue",
    image: "/grenite/mont-blue.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 81,
    name: "Moulin-Rouge",
    image: "/grenite/Moulin-Rouge.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 82,
    name: "Notte-Doro",
    image: "/grenite/Notte-Doro.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 83,
    name: "Oreo",
    image: "/grenite/Oreo.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 84,
    name: "P-White-Granite",
    image: "/grenite/P-White-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 85,
    name: "Pantagonia",
    image: "/grenite/Pantagonia-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 86,
    name: "Pebble Black",
    image: "/grenite/Pebble Black 2-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 88,
    name: "Polar-Blue",
    image: "/grenite/Polar-Blue.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 89,
    name: "Rajasthan-Black-Granite",
    image: "/grenite/Rajasthan-Black-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 90,
    name: "Red Marcus",
    image: "/grenite/Red Marcus.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 92,
    name: "River-Black-Granite",
    image: "/grenite/River-Black-Granite.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 93,
    name: "Rosewood",
    image: "/grenite/Rosewood.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 94,
    name: "Rosy-Pink",
    image: "/grenite/Rosy-Pink.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 95,
    name: "Sand-Brown",
    image: "/grenite/Sand-Brown.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 96,
    name: "Sensation",
    image: "/grenite/Sensation.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 97,
    name: "Splendor-Gold",
    image: "/grenite/Splendor-Gold.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 98,
    name: "Sunset",
    image: "/grenite/Sunset -p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 99,
    name: "Sunset canyon",
    image: "/grenite/Sunset canyon-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 101,
    name: "tan-brown",
    image: "/grenite/tan-brown.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 103,
    name: "Titanium-Gold",
    image: "/grenite/Titanium-Gold (1).jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 105,
    name: "Umari",
    image: "/grenite/Umari -p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 106,
    name: "Venezia-Gold",
    image: "/grenite/Venezia-Gold.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 107,
    name: "volcanic-grey",
    image: "/grenite/volcanic-grey.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 108,
    name: "Walnut-Jasper",
    image: "/grenite/Walnut-Jasper.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 109,
    name: "Web grey",
    image: "/grenite/Web grey-p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 110,
    name: "White knight",
    image: "/grenite/White knight -p-2000.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 111,
    name: "Alpine white",
    image: "/grenite/_Alpine white.jpg",
    category: "Granite",
    isNew: "true",
  },
  {
    id: 112,
    name: "Amazonite",
    image: "/marble/Amazonite.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 113,
    name: "Ambaji",
    image: "/marble/Ambaji-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 114,
    name: "Aqua-Black",
    image: "/marble/aqua-black-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 115,
    name: "Arbescato",
    image: "/marble/Arbescato.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 116,
    name: "Ash-Grey",
    image: "/marble/Ash-Grey.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 117,
    name: "Batch-Mermer",
    image: "/marble/Batch-Mermer-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 118,
    name: "Beige",
    image: "/marble/Beige.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 120,
    name: "Bruno-White",
    image: "/marble/Bruno-White-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 121,
    name: "Calacatta",
    image: "/marble/Calacatta.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 122,
    name: "Cappuccino-Marble",
    image: "/marble/Cappuccino-Marble_1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 123,
    name: "Carbon black ",
    image: "/marble/Carbon-black-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 124,
    name: "Cherry Gold Marble",
    image: "/marble/Cherry-Gold-Marble2.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 125,
    name: "Equator",
    image: "/marble/Equator.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 126,
    name: "Fantasy Brown",
    image: "/marble/Fantasy-Brown.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 127,
    name: "Flowery Gold Marble",
    image: "/marble/Flowery-Gold-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 128,
    name: "Giallo siena",
    image: "/marble/Giallo-siena.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 129,
    name: "Grafitto",
    image: "/marble/Grafitto.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 130,
    name: "reenmarble",
    image: "/marble/green-marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 131,
    name: "HIMALAYAN ONYX",
    image: "/marble/HIMALAYAN-ONYX.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 133,
    name: "Indian Serfinjinte ",
    image: "/marble/Indian-Serfinjinte-2.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 134,
    name: "Lady Onyx",
    image: "/marble/Lady-Onyx.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 135,
    name: "Magic Black",
    image: "/marble/Magic-Black.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 136,
    name: "Majestic Brown Copy",
    image: "/marble/Majestic-Brown-Copy.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 137,
    name: "Makrana White",
    image: "/marble/Makrana-White.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 138,
    name: "Matrix ",
    image: "/marble/Matrix-4.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 139,
    name: "Mercury Black ",
    image: "/marble/Mercury-Black-3.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 140,
    name: "Mercury White",
    image: "/marble/Mercury-White.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 141,
    name: "Millennium Grey ",
    image: "/marble/Millennium-Grey-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 142,
    name: "Ocean Black Marble ",
    image: "/marble/Ocean-Black-Marble-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 143,
    name: "Pink Marble Marble",
    image: "/marble/Pink-Marble-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 144,
    name: "Pistachino Marble ",
    image: "/marble/Pistachino-Marble-2.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 145,
    name: "Purple White Marble",
    image: "/marble/Purple-White-Marble-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 146,
    name: "R.White",
    image: "/marble/R.White-2.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 147,
    name: "Rain Forest Brown Marble",
    image: "/marble/Rain-Forest-Brown-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 148,
    name: "Rain Forest Gold Marble",
    image: "/marble/Rain-Forest-Gold-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 149,
    name: "Rain Forest Green Marble",
    image: "/marble/Rain-Forest-Green-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 150,
    name: "Red Fire Marble",
    image: "/marble/Red-Fire-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 151,
    name: "River Blue ",
    image: "/marble/River-Blue-3.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 152,
    name: "Rosso verona",
    image: "/marble/Rosso-verona.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 153,
    name: "Rosy Pink",
    image: "/marble/Rosy-Pink-1.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 154,
    name: "Scorpio Brown ",
    image: "/marble/Scorpio-Brown-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 155,
    name: "Scorpio",
    image: "/marble/Scorpio.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 156,
    name: "slabpandawhite",
    image: "/marble/slabpandawhite.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 157,
    name: "Sonal White ",
    image: "/marble/Sonal-White-2.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 158,
    name: "Spider Green",
    image: "/marble/Spider-Green.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 159,
    name: "Tick Black",
    image: "/marble/Tick-Black.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 160,
    name: "Tiger Stone",
    image: "/marble/Tiger-Stone.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 161,
    name: "Toronto Brown ",
    image: "/marble/Toronto-Brown-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 162,
    name: "Tra Onyx",
    image: "/marble/Tra-Onyx.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 163,
    name: "white marble",
    image: "/marble/white-marble.jpg",
    category: "Marble",
    isNew: "true",
  },
  {
    id: 164,
    name: "White Onyx",
    image: "/marble/White-Onyx-Marble.jpg",
    category: "Marble",
    isNew: "true",
  },

  {
    id: 165,
    name: "Bath Room",
    image: "/art/art19.jpg",
    category: "art",
    isNew: "true",
  },
  {
    id: 166,
    name: "Bath Room",
    image: "/art/art10.jpg",
    category: "art",
    isNew: "true",
  },
  {
    id: 167,
    name: "Tables",
    image: "/art/art23.jpg",
    category: "art",
    isNew: "true",
  },
  

];
const artCategory = [
  {
    id: "tables",
    number: 10,
    title: "Table",
    description: "Premium granite surfaces for countertops and flooring",
    image: "/art/art20.jpg",
  },
  {
    id: "lamps",
    number: 11,
    title: "Lamps",
    description: "Luxurious Lamps for countertops and flooring",
    image: "/art/art15.jpg",
  },
  {
    id: "pots",
    number: 1,
    title: "Pots",
    description: "Engineered products for modern interiar designs",
    image: "/art/art14.jpg",
  },
  {
    id: "tabletopwashbasins",
    number: 2,
    title: "Table Top Washbasins",
    description: "Engineered products for modern interiar designs",
    image: "/artphotos/washbasin.jpg",
  },
  {
    id: "marblebathroomsets",
    number: 3,
    title: "Marble Bathroom Sets",
    description: "Engineered products for modern interiar designs",
    image: "/artphotos/bathroomset.jpg",
  },
  {
    id: "marblebathtub",
    number: 4,
    title: "Marble Bathtub",
    description: "Engineered products for modern interiar designs",
    image: "/artphotos/bathtub.jpg",
  },
  {
    number: 5,
    id: "birdbaths",
    title: "Marble & Sandstone Birdbaths",
    description: "Engineered products for modern interiar designs",
    image: "/artphotos/birdbath.jpg",
  },
  {
    id: "coffeetable",
    number: 6,
    title: "Coffee & Centre Table",
    description: "Engineered products for modern interiar designs",
    image: "/artphotos/coffee.jpg",
  },
  {
    id: "consoletable",
    number: 7,
    title: "Console Table",
    description: "Engineered products for modern interiar designs",
    image: "/artphotos/console.jpg"
  },
  {
    id: "gardenbenches",
    number: 8,
    title: "Garden Benches ",
    description: "Engineered products for modern interiar designs",
    image: "/artphotos/gardenbench.jpg",

  },
  {
    number: 9,
    id: "sidecorner",
    title: "Side, Corner or tea table",
    description: "Engineered products for modern interiar designs",
    image: "/artphotos/sidetable.jpg",
  }
];


const Test = () => {
  const { categoryId }: { categoryId?: string } = useParams();
  const navigate = useNavigate();
  const handleProductClick = (productId: number) => {
    navigate(`/productsinfo/${productId}`);
  };
  const handleCategoryClick = (productId: string) => {
    navigate(`/artinfo/${productId}`,)
  };

  if (categoryId) {
    const categoryProducts = products.filter(
      (product) => product.category.toLowerCase() === categoryId.toLowerCase()
    );
    if (categoryId === "art") {
      return (
        <>
          <div className="container mx-auto px-4 py-16">
            <div className="grid md:grid-cols-3 gap-8">
              {artCategory.map((category) => (
                <CategoryCard
                  key={category.id}
                  title={category.title}
                  description={category.description}
                  image={category.image}
                  onClick={() => handleCategoryClick(category.id)}
                />
              ))}
            </div>
          </div>
        </>
      );
    }

    return (
      <ProductList
        products={categoryProducts}
        category={categoryId}
        onProductClick={handleProductClick}
      />
    );
  }
};

export default Test;
